### ISSUE TITLE
Exporting to cscope, ctags seems to crash starscope

### ISSUE THREAD

**Issue by jeelanp2003** [eapache/starscope#167]
```
/Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/bin/starscope  -e cscope gometa/ plasma/ indexing/ nitro/
Building: 695/695 Time: 00:00:02 ||==========================================>||
No changes detected.
Exporting to 'cscope.out' in format 'cscope'...
/Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:178:in `block in tokenize_line': undefined method `index' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:174:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:174:in `tokenize_line'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:110:in `block (2 levels) in export_cscope'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:108:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:108:in `block in export_cscope'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:100:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:100:in `export_cscope'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:33:in `export_to'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:23:in `block in export'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:22:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/lib/starscope/exportable.rb:22:in `export'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/bin/starscope:191:in `export'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/bin/starscope:235:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/bin/starscope:235:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/starscope-1.5.5/bin/starscope:235:in `<main>'
```

**Comment by eapache** [comment]
Hmm, it looks like your starscope db doesn't have the appropriate lines for some reason.
- what languages are the code you're indexing?
- can you share the `.starscope.db` file or the source code you're indexing generally?
- if you can't share those, can you try and narrow down the file that starscope is choking on by running it only on certain directories and seeing when it fails?

I can skip records when they're corrupt like this, which would fix the crash, but I think the result would just be an empty `cscope.out` file which isn't really any more helpful.

**Comment by eapache** [comment]
Closing as stale, please reopen if you can provide the necessary information.
