### ISSUE TITLE
Dropbox Update Throws No Such Directory

### ISSUE THREAD

**Issue by daBee** [eapache/starscope#194]
`Dropbox` on **Mac M1** was updated and a whole new `path` needs to be configured.  So I pointed `starscope` to that path and I'm now getting an error:

```
>>> 8:19:09 user3@myworkstation ~ ➜ starscope --force-update --quiet zz_before.rb zz_after.rb methods.rb /users/user3/RFS/ --export ctags, /Users/user3/Library/CloudStorage/Dropbox/Application\ Support/BBEdit/Completion\ Data/Ruby/ruby_tags
/Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `initialize': No such file or directory @ rb_sysopen -  (Errno::ENOENT)
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `open'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `export'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:190:in `export'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `block in <top (required)>'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `each'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `<top (required)>'
	from /Users/user3/.rbenv/versions/3.1.2/bin/starscope:25:in `load'
	from /Users/user3/.rbenv/versions/3.1.2/bin/starscope:25:in `<main>'
>>> 8:19:40 user3@myworkstation ~ ➜ l /Users/user3/Library/CloudStorage/Dropbox/Application\ Support/BBEdit/Completion\ Data/Ruby/
total 160
-rw-r--r--@ 1 user3  staff    11K  4 Oct 03:37 old_tags.zip
-rw-r--r--@ 1 user3  staff    66K 18 Oct 03:00 ruby_tags
>>> 8:20:45 user3@myworkstation ~ ➜
```

Even non-quiet, same issue:

```
>>> 8:20:45 user3@myworkstation ~ ➜ starscope --force-update zz_before.rb zz_after.rb methods.rb /users/user3/RF/RFS/ --export ctags, /Users/user3/Library/CloudStorage/Dropbox/Application\ Support/BBEdit/Completion\ Data/Ruby/ruby_tags
Building: 276/276 Time: 00:00:00 ||==========================================>||
No changes detected.
Exporting to '' in format 'ctags'...
/Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `initialize': No such file or directory @ rb_sysopen -  (Errno::ENOENT)
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `open'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/lib/starscope/exportable.rb:23:in `export'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:190:in `export'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `block in <top (required)>'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `each'
	from /Users/user3/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/starscope-1.6.1/bin/starscope:234:in `<top (required)>'
	from /Users/user3/.rbenv/versions/3.1.2/bin/starscope:25:in `load'
	from /Users/user3/.rbenv/versions/3.1.2/bin/starscope:25:in `<main>'
```

The error indicates the `directory`/`file` is not there, but it is, as I've demonstrated above.  Not sure how to fix this.

**Comment by eapache** [comment]
This is weird. Starscope doesn’t do any fancy processing of the file path or anything, it just calls Ruby’s `File.open` on the path you pass in. Maybe there’s a permission error or something which is being masked as the file not being present?

One thing I notice (maybe just an artefact of copying/pasting into github?) is that there’s a space after `ctags,` and before the path… this might be causing the argument parser to get confused? Arguments are space-separated, and `ctags,PATH` needs to be passed as a single argument (or any spaces escaped, as you do at several points in the path itself). Perhaps it would be clearer if I created a separate `—export-path` argument flag…

**Comment by daBee** [comment]
Just changed `permissions` to `755` on that target file.  Also took out `--force-update` and reduced source to a single file.  Same issue.  Checked the `path` to the target file and it's all `user3:staff`.  

Ah...the space was the culprit.  I inserted that coming back with the new path.  That structure had me 'correcting it'.  Ya if you changed that flag, it would be much clearer.

**Comment by eapache** [comment]
Done in https://github.com/eapache/starscope/commit/57beee3fdf0fbf9b1284ff69d384976803ca5262
